stages:
  - compile
  - test

before_script:
  - export CI_HOME="$( pwd )"
  - git submodule update --init --recursive
  - export SCRAM_ARCH="slc6_amd64_gcc530"
  - export CMSSW_VERSION="CMSSW_8_0_26_patch2"
  - source /cvmfs/cms.cern.ch/cmsset_default.sh
  - cd ..
  - scramv1 project CMSSW $CMSSW_VERSION
  - cd $CMSSW_VERSION/src
  - eval `scramv1 runtime -sh`
  - scram setup $CI_HOME/data/gsl.xml
  - cd $CI_HOME

compile:
  stage: compile
  script:
    - cd $CMSSW_BASE/src
    - cp -r $CI_HOME DNN
    - source DNN/setup.sh
    - scram b
    - cd $CMSSW_BASE
    - find src -maxdepth 3 -type d | grep -e "^src/.*/.*/\(interface\|data\|python\)" | tar -czf $CI_HOME/cmssw.tgz lib biglib bin --exclude="*.pyc" --files-from -
  artifacts:
    paths:
      - cmssw.tgz
    name: "${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}"
    expire_in: 10 minutes

test:
  stage: test
  script:
    - cd $CMSSW_BASE
    - tar -xzf $CI_HOME/cmssw.tgz
    - cd src
    - scram b python
    - cd $CI_HOME
    - test_tftensor && test_tfgraph
